NET_INFO_PATH : ./config.yml
EXPERIMENT_NAME : jyjung_test
IS_GPU : 1 # 0: not use GPU / 1: use GPU

TEST : 0
TRAINING : 1
VALIDATION : 2

#path
DATASET_PATH : ./Dataset/
SAVE_PATH : model

#DataShape (PU)
PU_SIZE : [8, 32]
QP_LIST : [22, 32]
MODE_NUM : [11, 6]

# enable to change : INIT_LEARNING_RATE / PRINT_PERIOD / BATCH_SIZE / OBJECT_EPOCH / NUM_WORKER(thread 개수/2)
INIT_LEARNING_RATE : 0.001
PRINT_PERIOD : 1000
DATASET_NUM : 200000
BATCH_SIZE : 120
OBJECT_EPOCH: 50
GPU_MONITOR: 1
NUM_WORKER : 12